spring:
  application:
    name: service-two
  jackson:
    serialization:
      indent_output: true
  kafka:
    consumer:
      bootstrap-servers: 130.193.50.65:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081

